import {
    ShoppingCart,
    Monitor,
    MessageCircle,
    Printer,
    Package,
    ShoppingBag,
    Megaphone,
    Store,
    Code,
    FileCode,
    Palette,
    Search,
    BarChart,
    Globe,
    Share2,
    PenTool,
    Layers,
    Sparkles,
    Camera,
ThumbsUp,
    FileText,
} from "lucide-react";

export const iconMap = {
    "shopping-cart": ShoppingCart,
    monitor: Monitor,
    "message-circle": MessageCircle,
    printer: Printer,
    package: Package,
    "shopping-bag": ShoppingBag,
    megaphone: Megaphone,
    store: Store,
    code: Code,
    "file-code": FileCode,
    palette: Palette,
    search: Search,
    "bar-chart": BarChart,
    globe: Globe,
    "share-2": Share2,
    "pen-tool": PenTool,
    layers: Layers,
    sparkles: Sparkles,
    instagram: Camera,
    facebook: ThumbsUp,
    "file-text": FileText,
};